Implemented make-gitlab-user command

diff --git a/dfst b/dfst
--- a/dfst
+++ b/dfst
@@ -167,6 +167,37 @@ elif [ "$1" = "getdemo" ]; then
      $(docker cp "demo-content:/opt/dita-community/data/Thunderbird" "${targetDir}")
      exit $?
   fi
+elif [ "$1" = "make-gitlab-user" ]; then
+  if [ -z "${GITLAB_PRIVATE_TOKEN}" ]; then
+     echo "Environment variable 'GITLAB_PRIVATE_TOKEN' not set. You must set this"
+     echo "variable to the GitLab private token for your GitLab server. See DFST documentation."
+     exit 1;
+  fi
+  username="$USER"
+  password="password"
+  if [ "$2" != "" ]; then
+     username=$2
+  fi
+  if [ "$3" != "" ]; then
+     password=$3
+  fi
+  echo "Creating GitLab user \"${username}\"..."
+  result=$(curl -s -X POST --header "PRIVATE-TOKEN: ${GITLAB_PRIVATE_TOKEN}" "http://${HOSTNAME}:${GITLAB_PORT}/api/v3/users?username=${username}&email=${username}@example.com&password=${password}&name=${username}")
+  if [[ "$result" =~ "{\"message\":\"401 Unauthorized\"" ]]; then
+     echo "Failure: Did not authenticate using private token \"${GITLAB_PRIVATE_TOKEN}\"."
+     exit 1;
+  elif [[ "$result" =~ "404 Not Found" ]]; then
+     echo "Failure: Host \"${HOSTNAME}:${GITLAB_PORT}\" does not  appear to have GitLab running."
+     exit 1;
+  elif [[ "$result" =~ "{\"name\":\"${username}\",\"username\":\"${username}\"" ]]; then
+     echo "Success: User \"${username}\" created with password \"${password}\""
+     exit 0;
+  else 
+     echo "Failure: Doesn't look like the GitLab connection worked but the failure is not an expected one."
+     echo "Got response \"${result}\""
+     exit 1;
+  fi
+  
 elif [ "$1" = "test-gitlab" ]; then
   echo "Testing GitLab connection..."
   if [ -z "${GITLAB_PRIVATE_TOKEN}" ]; then
